Repository debionetwork/debio-background-worker, pull requests merged in 2022-09, with the labels that each got.

#148 fix: send reward for staking
  package-lock.json
  package.json
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
Labels: fix

#149 ci: improve docker builder smaller size
  .dockerignore
  .maintain/docker/Dockerfile
  package-lock.json
Labels: ci

#151 fix: notification for reward
  src/common/mailer/mailer.module.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.ts
  src/listeners/substrate-listener/commands/genetic-testing/data-staked/data-staked.handler.ts
  src/listeners/substrate-listener/commands/genetic-testing/dna-sample-rejected/dna-sample-rejected.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
  test/e2e/listener-test-sequencer.js
  test/e2e/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-events.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-registered.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-testing/dna-sample-rejected.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-testing/dna-sample-result-ready.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-testing/genetic-testing-events.spec.ts
  test/e2e/listeners/substrate-listener/commands/labs/labs-events.spec.ts
  test/e2e/listeners/substrate-listener/commands/labs/stake-successful.spec.ts
  test/e2e/listeners/substrate-listener/commands/labs/unstake-successful.spec.ts
  test/e2e/listeners/substrate-listener/commands/orders/order-failed.spec.ts
  test/e2e/listeners/substrate-listener/commands/orders/order-fulfilled.spec.ts
  test/e2e/listeners/substrate-listener/commands/orders/orders-events.spec.ts
  test/e2e/listeners/substrate-listener/commands/service-request/service-request-claimed.spec.ts
  test/e2e/listeners/substrate-listener/commands/service-request/service-request-events.spec.ts
  test/e2e/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded.spec.ts
Labels: fix

#152 fix: Change submit verification notification 'from' and 'to' for lab and GA
  src/common/debio-conversion/debio-conversion.service.ts
  src/listeners/ethereum-listener/ethereum-listener.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-cancelled/genetic-analysis-order-cancelled.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysys-order-created/genetic-analysis-order-created.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-rejected/genetic-analysis-rejected.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-resultready/genetic-analysis-result-ready.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-staked/genetic-analyst-staked.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-unstake/genetic-analyst-unstaked.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-verification-status/genetic-analyst-verification-status.handler.ts
  src/listeners/substrate-listener/commands/genetic-testing/data-staked/data-staked.handler.ts
  src/listeners/substrate-listener/commands/labs/registered/lab-registered.handler.ts
  src/listeners/substrate-listener/commands/labs/retrieve-unstake-amount/retrieve-unstake-amount.handler.ts
  src/listeners/substrate-listener/commands/labs/stake-successfull/stake-successful.handler.ts
  src/listeners/substrate-listener/commands/labs/unstake-successfull/unstaked-successful.handler.ts
  src/listeners/substrate-listener/commands/labs/update-verification-status/update-verification-status.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-waiting-for-unstaked/service-request-waiting-for-unstaked.handler.ts
  src/listeners/substrate-listener/commands/services/service-created/service-created.handler.ts
  test/e2e/listener-test-sequencer.js
  test/e2e/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-events.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-events.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analyst-service/genetic-analyst-service-events.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-events.spec.ts
  test/e2e/listeners/substrate-listener/commands/orders/orders-events.spec.ts
  test/e2e/listeners/substrate-listener/commands/services/services-events.spec.ts
  test/mock/models/genetic-analysts/genetic-analysts.mock.ts
  test/unit/listeners/substrate-listener/commands/lab/lab-unstaked-successful/lab-unstaked-successful.handler.spec.ts
Labels: fix

#122 feat: gas limit error logging
  src/common/error-logging/dto/error-logging.dto.ts
  src/common/error-logging/error-logging.module.ts
  src/common/error-logging/error-logging.service.ts
  src/common/error-logging/index.ts
  src/common/error-logging/models/error-logging.entity.ts
  src/common/error-logging/models/response.ts
  src/common/escrow/escrow.module.ts
  src/common/escrow/escrow.service.ts
  src/listeners/ethereum-listener/ethereum-listener.module.ts
  test/unit/common/modules/error-logging/error-logging.service.spec.ts
  test/unit/common/modules/escrow/escrow.service.spec.ts
  test/unit/mock.ts
Labels: fix, feature, improvement

#155 ci: fix deployer
  .github/workflows/deployer.yaml
Labels: ci

#156 ci: fix reusable workflow
  .github/workflows/builder.yaml
  .github/workflows/deployer.yaml
Labels: ci

#157 ci: fix passing secrets
  .github/workflows/deployer.yaml
Labels: ci

#158 ci: fix passing secrets to workflow
  .github/workflows/deployer.yaml
Labels: ci

#159 ci: fix use wrong secret key
  .github/workflows/builder.yaml
  .github/workflows/deployer.yaml
Labels: ci

#161 ci: fixed ssh args
  .github/workflows/deployer.yaml
Labels: ci

#162 ci: fix unsupported ssh args
  .github/workflows/deployer.yaml
Labels: ci

#163 ci: move ssh args to flags
  .github/workflows/deployer.yaml
Labels: ci

#164 ci: fixed ssh flags
  .github/workflows/deployer.yaml
Labels: ci

#165 ci: removed unused ssh flags
  .github/workflows/deployer.yaml
Labels: ci

#166 ci: ssh debug
  .github/workflows/deployer.yaml
Labels: ci

#167 ci: fix ssh debug
  .github/workflows/deployer.yaml
Labels: ci

#169 ci: fixed deployment image tag
  .github/workflows/deployer.yaml
Labels: ci

#170 ci: bump scorecard to v2
  .github/dependabot.yaml
  .github/pull_request_template.md
  .github/workflows/analyzer.yaml
Labels: ci

#174 ci: fix changelog builder credentials
  .github/workflows/releaser.yaml
Labels: ci

#175 ci: fixed docker builder
  .github/pull_request_template.md
  .github/workflows/builder.yaml
  .github/workflows/mlc_config.json
Labels: ci

#153 fix: update order fulfilled
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
Labels: fix

#176 ci: cleanup ssh tunneling
  .github/workflows/deployer.yaml
  README.md
Labels: ci

#177 feat: add menstrual calendar event handler
  src/indexer/events/menstrual-calendar/commands/menstrual-calendar-added/menstrual-calendar-added.command.ts
  src/indexer/events/menstrual-calendar/commands/menstrual-calendar-added/menstrual-calendar-added.handler.ts
  src/indexer/events/menstrual-calendar/commands/menstrual-calendar-removed/menstrual-calendar-removed.command.ts
  src/indexer/events/menstrual-calendar/commands/menstrual-calendar-removed/menstrual-calendar-removed.handler.ts
  src/indexer/events/menstrual-calendar/commands/menstrual-calendar-updated/menstrual-calendar-updated.command.ts
  src/indexer/events/menstrual-calendar/commands/menstrual-calendar-updated/menstrual-calendar-updated.handler.ts
  src/indexer/events/menstrual-calendar/commands/menstrual-cycle-log-added/menstrual-cycle-log-added.command.ts
  src/indexer/events/menstrual-calendar/commands/menstrual-cycle-log-added/menstrual-cycle-log-added.handler..ts
  src/indexer/events/menstrual-calendar/commands/menstrual-cycle-log-removed/menstrual-cycle-log-removed.command.ts
  src/indexer/events/menstrual-calendar/commands/menstrual-cycle-log-removed/menstrual-cycle-log-removed.handler.ts
  src/indexer/events/menstrual-calendar/commands/menstrual-cycle-log-updated/menstrual-cycle-log-updated.command.ts
  src/indexer/events/menstrual-calendar/commands/menstrual-cycle-log-updated/menstrual-cycle-log-updated.handler.ts
  src/indexer/events/menstrual-calendar/index.ts
  src/indexer/indexer.routes.ts
  src/indexer/models/menstrual-calendar/menstrual-calendar.ts
  src/indexer/models/menstrual-calendar/menstrual-cycle-log.ts
  src/indexer/models/service-request/service-invoice.ts
  src/indexer/models/service-request/service-price.ts
  test/e2e/indexer/events/menstrual-calendar-events.spec.ts
  test/unit/indexer/events/service-request/service-request.handler.spec.ts
Labels: feature
