Repository debionetwork/debio-background-worker, pull requests merged in 2022-08, with the labels that each got.

#136 fix: Change wording for entity, desc, and type notification
  src/common/notification/models/response.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-verification-status/genetic-analyst-verification-status.handler.ts
  src/listeners/substrate-listener/commands/orders/order-created/order-created.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.spec.ts
Labels: fix

#138 feat: email notification for lab and ga order
  nest-cli.json
  src/common/mailer/mailer.manager.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
  src/listeners/substrate-listener/models/new-order-ga.model.ts
  src/listeners/substrate-listener/models/new-order-lab.model.ts
  src/listeners/substrate-listener/templates/new-order-ga.hbs
  src/listeners/substrate-listener/templates/new-order-lab.hbs
  test/e2e/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid.spec.ts
  test/e2e/listeners/substrate-listener/commands/orders/order-paid.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.spec.ts
Labels: feature, test

#141 improvement: enhance notification model and query notification
  src/common/notification/dto/notification.dto.ts
  src/common/notification/models/notification.entity.ts
  src/common/notification/notification.service.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysys-order-created/genetic-analysis-order-created.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-rejected/genetic-analysis-rejected.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-resultready/genetic-analysis-result-ready.handler.ts
  src/listeners/substrate-listener/commands/genetic-analyst-services/genetic-analyst-service-created/genetic-analyst-service-created.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-registered/genetic-analyst-registered.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-verification-status/genetic-analyst-verification-status.handler.ts
  src/listeners/substrate-listener/commands/genetic-testing/dna-sample-rejected/dna-sample-rejected.handler.ts
  src/listeners/substrate-listener/commands/genetic-testing/dna-sample-result-ready/dna-sample-result-ready.handler.ts
  src/listeners/substrate-listener/commands/labs/registered/lab-registered.handler.ts
  src/listeners/substrate-listener/commands/labs/update-verification-status/update-verification-status.handler.ts
  src/listeners/substrate-listener/commands/orders/order-created/order-created.handler.ts
  src/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
  src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-claimed/service-request-claimed.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-excess/service-request-excess.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-partial/service-request-partial.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded/service-request-staking-amount-refunded.handler.ts
  src/listeners/substrate-listener/commands/services/service-created/service-created.handler.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-created.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-rejected.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analyst-service/genetic-analyst-service-created.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-testing/dna-sample-rejected.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-testing/dna-sample-result-ready.spec.ts
  test/e2e/listeners/substrate-listener/commands/orders/order-paid.spec.ts
  test/e2e/listeners/substrate-listener/commands/service-request/service-request-excess.spec.ts
  test/e2e/listeners/substrate-listener/commands/service-request/service-request-partial.spec.ts
  test/e2e/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded.spec.ts
  test/e2e/listeners/substrate-listener/commands/services/service-created.spec.ts
  test/mock/models/notification/notification.entity.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analyst-services/genetic-analyst-service-created/genetic-analyst-service-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-testing/dna-sample-rejected/dna-sample-rejected.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-testing/dna-sample-result-ready/dna-sample-result-ready.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded/service-request-staking-amount-refunded.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/services/service-created/service-created.handler.spec.ts
Labels: improvement

#139 test: integration test genetic analyst
  test/e2e/indexer-test-sequencer.js
  test/e2e/indexer/events/genetic-analysis-events.spec.ts
  test/e2e/indexer/events/genetic-analysis-order-events.spec.ts
  test/e2e/indexer/events/genetic-analyst-qualification-events.spec.ts
  test/e2e/indexer/events/genetic-analyst-service-events.spec.ts
Labels: test

#146 chore: bump version to 2.1.7
  package-lock.json
  package.json
Labels: feature
