Repository debionetwork/debio-background-worker, pull requests merged in 2022-03, with the labels that each got.

#88 ci: optimize deployment resource request & limit
  .github/workflows/deployer.yml
Labels: ci

#89 feat: git hooks
  .maintain/install-hooks.sh
  package-lock.json
  package.json
  src/substrate/events/certifications/commands/certification-deleted/certification-deleted.handler.ts
  src/substrate/events/certifications/commands/certification-updated/certification-updated.handler.ts
  src/substrate/events/genetic-analyst-qualifications/commands/genetic-analysts-qualification-deleted/genetic-analysts-qualification-deleted.handler.ts
  src/substrate/events/genetic-analyst-qualifications/commands/genetic-analysts-qualification-updated/genetic-analysts-qualification-updated.handler.ts
  src/substrate/events/service-request/commands/claimed-service-request/claimed-service-request.handler.ts
  src/substrate/events/service-request/commands/create-service-request/create-service-request.handler.ts
  src/substrate/events/service-request/commands/finalized-service-request/finalized-service-request.handler.ts
  src/substrate/events/service-request/commands/processed-service-request/processed-service-request.handler.ts
  src/substrate/events/service-request/commands/unstaked-service-request/unstaked-service-request.handler.ts
  src/substrate/events/services/commands/service-deleted/service-deleted.handler.ts
  src/substrate/substrate.handler.ts
  test/unit/events/genetic-analysts/genetic-analysts.command.spec.ts
  test/unit/events/service-request/service-request.handler.spec.ts
  test/unit/mock.ts
Labels: feature, ci, test

#90 [DBIO-2217] Clean Lint Warnings
  src/ethereum/ethereum.module.ts
  src/ethereum/request-service/blocks/commands/set-last-request-service-block/set-last-request-service-block.command.ts
  src/ethereum/request-service/blocks/commands/set-last-request-service-block/set-last-request-service-block.handler.ts
  src/ethereum/request-service/blocks/index.ts
  src/ethereum/request-service/blocks/queries/get-last-request-service-block/get-last-request-service-block.handler.ts
  src/ethereum/request-service/blocks/queries/get-last-request-service-block/get-last-request-service-block.query.ts
  src/ethereum/request-service/request-service-abi.json
  src/ethereum/request-service/request-service.handler.ts
  src/ethereum/request-service/request-service.module.ts
  src/ethereum/request-service/request-service.spec.ts
  src/ethereum/request-service/request-service/commands/create-service-request/create-service-request.command.ts
  src/ethereum/request-service/request-service/commands/create-service-request/create-service-request.handler.ts
  src/ethereum/request-service/request-service/commands/request-claimed/request-claimed.command.ts
  src/ethereum/request-service/request-service/commands/request-claimed/request-claimed.handler.ts
  src/ethereum/request-service/request-service/index.ts
  src/ethereum/request-service/request-service/models/blockMetadata.ts
  src/ethereum/request-service/request-service/models/claimRequest.ts
  src/ethereum/request-service/request-service/models/request.ts
  src/substrate/events/genetic-testing/commands/dna-sample-arrived/dna-sample-arrived.command.ts
  src/substrate/events/genetic-testing/commands/dna-sample-arrived/dna-sample-arrived.handler.ts
  src/substrate/events/genetic-testing/commands/dna-sample-quality-controlled/dna-sample-quality-controlled.command.ts
  src/substrate/events/genetic-testing/commands/dna-sample-quality-controlled/dna-sample-quality-controlled.handler.ts
  src/substrate/events/genetic-testing/commands/dna-sample-registered/dna-sample-registered.command.ts
  src/substrate/events/genetic-testing/commands/dna-sample-registered/dna-sample-registered.handler.ts
  src/substrate/events/genetic-testing/commands/dna-sample-rejected/dna-sample-rejected.command.ts
  src/substrate/events/genetic-testing/commands/dna-sample-rejected/dna-sample-rejected.handler.ts
  src/substrate/events/genetic-testing/commands/dna-sample-result-ready/dna-sample-result-ready.command.ts
  src/substrate/events/genetic-testing/commands/dna-sample-result-ready/dna-sample-result-ready.handler.ts
  src/substrate/events/genetic-testing/commands/dna-test-result-submitted/dna-test-result-submitted.command.ts
  src/substrate/events/genetic-testing/commands/dna-test-result-submitted/dna-test-result-submitted.handler.ts
  src/substrate/events/orders/commands/order-failed/order-failed.handler.ts
  src/substrate/events/service-request/commands/claimedwaiting-service-request/claimedwaiting-service-request.command.ts
  src/substrate/events/service-request/commands/claimedwaiting-service-request/claimedwaiting-service-request.handler.ts
  src/substrate/events/service-request/commands/create-service-request/create-service-request.handler.ts
  src/substrate/events/service-request/commands/increased-service-request/increased-service-request.command.ts
  src/substrate/events/service-request/commands/increased-service-request/increased-service-request.handler.ts
  src/substrate/events/service-request/commands/refunded-service-request/refunded-service-request.command.ts
  src/substrate/events/service-request/commands/refunded-service-request/refunded-service-request.handler.ts
  src/substrate/events/services/models/service-info.ts
  src/substrate/models/genetic-analysts/genetic-analysts.info.ts
  src/substrate/substrate.handler.ts
  test/unit/events/certifications/certifications.command.spec.ts
  test/unit/events/genetic-analysis-order/genetic-analysis-order.command.spec.ts
  test/unit/events/genetic-analysis/genetic-analysis.command.spec.ts
  test/unit/events/genetic-analyst-qualifications/genetic-analyst-qualifications.command.spec.ts
  test/unit/events/genetic-analyst-services/genetic-analyst-services.command.spec.ts
  test/unit/events/genetic-analysts/genetic-analysts.command.spec.ts
  test/unit/events/genetic-data/genetic-data.command.spec.ts
  test/unit/events/genetic-testing/genetic-testing.command.spec.ts
  test/unit/events/labs/labs.command.spec.ts
  test/unit/events/orders/orders.command.spec.ts
  test/unit/events/service-request/service-request.command.spec.ts
  test/unit/events/services/services.command.spec.ts
Labels: improvement

#91 [DBIO-2223] ci: google auth with workload identity federation
  .github/workflows/builder.yml
  .github/workflows/deployer.yml
  .github/workflows/tester.yml
Labels: ci
