Repository debionetwork/debio-background-worker, pull requests merged in 2022-10, with the labels that each got.

#180 fix: menstrual calendar and fix id
  src/indexer/indexer.module.ts
Labels: fix

#181 ci: improvements
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yaml
  .github/pull_request_template.md
  .github/workflows/analyzer.yaml
  .github/workflows/builder.yaml
  .github/workflows/cicd.yaml
  .github/workflows/cii.yaml
  .github/workflows/deployer.yaml
  .github/workflows/mlc_config.json
  .github/workflows/rcb_config.json
  .github/workflows/releaser.yaml
  .github/workflows/sast.yaml
  .github/workflows/tester.yaml
  .maintain/docker/Dockerfile
  .maintain/install-hooks.sh
  CODEOWNERS
  README.md
  package.json
  types.json
Labels: ci

#195 feat: update service request listener and indexer
  src/indexer/events/service-request/commands/claimed-service-request/claimed-service-request.command.ts
  src/indexer/events/service-request/commands/claimed-service-request/claimed-service-request.handler.ts
  src/indexer/events/service-request/commands/finalized-service-request/finalized-service-request.command.ts
  src/indexer/events/service-request/commands/finalized-service-request/finalized-service-request.handler.ts
  src/indexer/events/service-request/commands/processed-service-request/processed-service-request.command.ts
  src/indexer/events/service-request/commands/unstaked-service-request/unstaked-service-request.command.ts
  src/indexer/events/service-request/commands/unstaked-service-request/unstaked-service-request.handler.ts
  src/indexer/events/service-request/commands/unstakedwaiting-service-request/unstakedwaiting-service-request.command.ts
  src/indexer/events/service-request/commands/unstakedwaiting-service-request/unstakedwaiting-service-request.handler.ts
  src/indexer/events/service-request/commands/update-service-request/update-service-request.command.ts
  src/indexer/events/service-request/commands/update-service-request/update-service-request.handler.ts
  src/indexer/events/service-request/index.ts
  src/indexer/indexer.routes.ts
  src/indexer/models/service-request/update-service-request.ts
  src/listeners/substrate-listener/commands/service-request/index.ts
  src/listeners/substrate-listener/commands/service-request/service-request-updated/service-request-updated.command.ts
  src/listeners/substrate-listener/commands/service-request/service-request-updated/service-request-updated.handler.ts
  test/unit/indexer/events/service-request/service-request.command.spec.ts
  test/unit/indexer/events/service-request/service-request.handler.spec.ts
Labels: improvement

#197 feat: add command handler menstrual subscription event
  src/indexer/events/menstrual-calendar/commands/menstrual-calendar-updated/menstrual-calendar-updated.handler.ts
  src/indexer/events/menstrual-subscription/commands/menstrual-subscription-added/menstrual-subscription-added.command.ts
  src/indexer/events/menstrual-subscription/commands/menstrual-subscription-added/menstrual-subscription-added.handler.ts
  src/indexer/events/menstrual-subscription/commands/menstrual-subscription-paid/menstrual-subscription-paid.command.ts
  src/indexer/events/menstrual-subscription/commands/menstrual-subscription-paid/menstrual-subscription-paid.handler.ts
  src/indexer/events/menstrual-subscription/commands/menstrual-subscription-price-added/menstrual-subscription-price-added.command.ts
  src/indexer/events/menstrual-subscription/commands/menstrual-subscription-price-added/menstrual-subscription-price-added.handler.ts
  src/indexer/events/menstrual-subscription/commands/menstrual-subscription-updated/menstrual-subscription-updated.command.ts
  src/indexer/events/menstrual-subscription/commands/menstrual-subscription-updated/menstrual-subscription-updated.handler.ts
  src/indexer/events/menstrual-subscription/index.ts
  src/indexer/indexer.module.ts
  src/indexer/indexer.routes.ts
  src/indexer/models/menstrual-subscription/menstrual-subscription-duration.ts
  src/indexer/models/menstrual-subscription/menstrual-subscription-price.ts
  src/indexer/models/menstrual-subscription/menstrual-subscription-status.ts
  src/indexer/models/menstrual-subscription/menstrual-subscription.ts
  src/indexer/models/menstrual-subscription/payment-status.ts
Labels: improvement

#194 feat: update notification order fulfilled with dynamic currency
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
Labels: improvement
