Repository debionetwork/debio-background-worker, pull requests merged in 2022-02, with the labels that each got.

#76 [DBIO-1781] ci: add nodeSelector to deployment
  .github/workflows/deploy.yml
Labels: CI

#73 [DBIO-1683] Create index Genetic Analyst certifications
  src/substrate/events/genetic-analyst-qualifications/commands/genetic-analysts-qualification-created/genetic-analysts-qualification-created.command.ts
  src/substrate/events/genetic-analyst-qualifications/commands/genetic-analysts-qualification-created/genetic-analysts-qualification-created.handler.ts
  src/substrate/events/genetic-analyst-qualifications/commands/genetic-analysts-qualification-deleted/genetic-analysts-qualification-deleted.command.ts
  src/substrate/events/genetic-analyst-qualifications/commands/genetic-analysts-qualification-deleted/genetic-analysts-qualification-deleted.handler.ts
  src/substrate/events/genetic-analyst-qualifications/commands/genetic-analysts-qualification-updated/genetic-analysts-qualification-updated.command.ts
  src/substrate/events/genetic-analyst-qualifications/commands/genetic-analysts-qualification-updated/genetic-analysts-qualification-updated.handler.ts
  src/substrate/events/genetic-analyst-qualifications/index.ts
  src/substrate/models/genetic-analysts-qualifications/genetic-analysts-qualifications.certificate.ts
  src/substrate/models/genetic-analysts-qualifications/genetic-analysts-qualifications.experience.ts
  src/substrate/models/genetic-analysts-qualifications/genetic-analysts-qualifications.info.ts
  src/substrate/models/genetic-analysts-qualifications/genetic-analysts-qualifications.model.ts
  src/substrate/substrate.handler.ts
  src/substrate/substrate.module.ts
  test/unit/events/genetic-analyst-qualifications/genetic-analyst-qualifications.command.spec.ts
  test/unit/events/genetic-analyst-qualifications/genetic-analyst-qualifications.handler.spec.ts
Labels: enhancement

#74 [DBIO-1714] Create index genetic analysis tracking + unit testing
  src/substrate/events/genetic-analysis/commands/genetic-analysis-in-progress/genetic-analysis-in-progress.command.ts
  src/substrate/events/genetic-analysis/commands/genetic-analysis-in-progress/genetic-analysis-in-progress.handler.ts
  src/substrate/events/genetic-analysis/commands/genetic-analysis-rejected/genetic-analysis-rejected.command.ts
  src/substrate/events/genetic-analysis/commands/genetic-analysis-rejected/genetic-analysis-rejected.handler.ts
  src/substrate/events/genetic-analysis/commands/genetic-analysis-result-ready/genetic-analysis-result-ready.command.ts
  src/substrate/events/genetic-analysis/commands/genetic-analysis-result-ready/genetic-analysis-result-ready.handler.ts
  src/substrate/events/genetic-analysis/commands/genetic-analysis-submitted/genetic-analysis-submitted.command.ts
  src/substrate/events/genetic-analysis/commands/genetic-analysis-submitted/genetic-analysis-submitted.handler.ts
  src/substrate/events/genetic-analysis/index.ts
  src/substrate/models/genetic-analysis/genetic-analysis.model.ts
  src/substrate/models/genetic-analysis/genetic-analysis.status.ts
  test/unit/events/genetic-analysis/genetic-analysis.command.spec.ts
  test/unit/events/genetic-analysis/genetic-analysis.handler.spec.ts
Labels: enhancement

#78 fix: currency type.
  src/substrate/models/currencyType.ts
Labels: bug

#70 [DBIO-1634] ci: unit test in pipeline.
  .github/workflows/pull-request.yml
Labels: CI

#75 [DBIO-1715 & DBIO-1730] Create & Update index genetic analysis order + Unit Testing
  src/substrate/events/genetic-analysis-order/commands/genetic-analysis-order-cancelled/genetic-analysis-order-cancelled.command.ts
  src/substrate/events/genetic-analysis-order/commands/genetic-analysis-order-cancelled/genetic-analysis-order-cancelled.handler.ts
  src/substrate/events/genetic-analysis-order/commands/genetic-analysis-order-created/genetic-analysis-order-created.command.ts
  src/substrate/events/genetic-analysis-order/commands/genetic-analysis-order-created/genetic-analysis-order-created.handler.ts
  src/substrate/events/genetic-analysis-order/commands/genetic-analysis-order-failed/genetic-analysis-order-failed.command.ts
  src/substrate/events/genetic-analysis-order/commands/genetic-analysis-order-failed/genetic-analysis-order-failed.handler.ts
  src/substrate/events/genetic-analysis-order/commands/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.command.ts
  src/substrate/events/genetic-analysis-order/commands/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.ts
  src/substrate/events/genetic-analysis-order/commands/genetic-analysis-order-paid/genetic-analysis-order-paid.command.ts
  src/substrate/events/genetic-analysis-order/commands/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.ts
  src/substrate/events/genetic-analysis-order/commands/genetic-analysis-order-refunded/genetic-analysis-order-refunded.command.ts
  src/substrate/events/genetic-analysis-order/commands/genetic-analysis-order-refunded/genetic-analysis-order-refunded.handler.ts
  src/substrate/events/genetic-analysis-order/index.ts
  src/substrate/events/genetic-analysis/commands/genetic-analysis-result-ready/genetic-analysis-result-ready.handler.ts
  src/substrate/events/genetic-analyst-qualifications/commands/genetic-analysts-qualification-created/genetic-analysts-qualification-created.handler.ts
  src/substrate/events/genetic-analyst-qualifications/commands/genetic-analysts-qualification-deleted/genetic-analysts-qualification-deleted.handler.ts
  src/substrate/events/genetic-analyst-qualifications/commands/genetic-analysts-qualification-updated/genetic-analysts-qualification-updated.handler.ts
  src/substrate/events/genetic-analyst-services/commands/genetic-analyst-services-created/genetic-analyst-services-created.handler.ts
  src/substrate/events/genetic-analyst-services/commands/genetic-analyst-services-deleted/genetic-analyst-services-deleted.handler.ts
  src/substrate/events/genetic-analyst-services/commands/genetic-analyst-services-updated/genetic-analyst-services-updated.handler.ts
  src/substrate/events/genetic-analysts/commands/genetic-analysts-stake-successful/genetic-analysts-stake-successful.command.ts
  src/substrate/events/genetic-analysts/commands/genetic-analysts-stake-successful/genetic-analysts-stake-successful.handler.ts
  src/substrate/events/genetic-analysts/commands/genetic-analysts-update-verification-status/genetic-analysts-update-verification-status.command.ts
  src/substrate/events/genetic-analysts/commands/genetic-analysts-update-verification-status/genetic-analysts-update-verification-status.handler.ts
  src/substrate/models/currencyType.ts
  src/substrate/models/genetic-analysis-order/genetic-analysis-order.model.ts
  src/substrate/models/genetic-analysis-order/genetic-analysis-order.status.ts
  src/substrate/models/genetic-analysts-qualifications/genetic-analysts-qualifications.info.ts
  src/substrate/models/genetic-analysts/genetic-analysts.model.ts
  src/substrate/models/verificationStatus.ts
  src/substrate/substrate.handler.ts
  src/substrate/substrate.module.ts
  test/unit/events/genetic-analysis-order/genetic-analysis-order.command.spec.ts
  test/unit/events/genetic-analysis-order/genetic-analysis-order.handler.spec.ts
  test/unit/events/genetic-analysis/genetic-analysis.handler.spec.ts
  test/unit/events/genetic-analyst-qualifications/genetic-analyst-qualifications.handler.spec.ts
  test/unit/events/genetic-analyst-services/genetic-analyst-services.handler.spec.ts
  test/unit/events/genetic-analysts/genetic-analysts.command.spec.ts
  test/unit/events/genetic-analysts/genetic-analysts.handler.spec.ts
  test/unit/events/genetic-data/genetic-data.handler.spec.ts
  test/unit/events/genetic-testing/genetic-testing.command.spec.ts
  test/unit/mock.ts
  test/unit/substrate.spec.ts
Labels: enhancement

#83 ci: enable autoscaling
  .github/workflows/deployer.yml
  .github/workflows/tester.yml
  LICENSE
Labels: CI

#84 [DBIO-1614] feat : Convert hex to string before input to elasticsearch
  package.json
  src/substrate/events/labs/models/lab-info.ts
  src/substrate/events/service-request/models/request.ts
  src/substrate/models/util.ts
Labels: enhancement
