Repository debionetwork/debio-background-worker, pull requests merged in 2022-12, with the labels that each got.

#221 fix: add menstrual subscription index when initialize
  src/indexer/indexer.handler.ts
Labels: fix

#227 feat: transaction log menstrual subscription
  src/common/transaction-logging/dto/transaction-logging.dto.ts
  src/indexer/events/menstrual-calendar/commands/menstrual-cycle-log-added/menstrual-cycle-log-added.command.ts
  src/indexer/events/menstrual-calendar/commands/menstrual-cycle-log-added/menstrual-cycle-log-added.handler..ts
  src/indexer/events/menstrual-calendar/index.ts
  src/indexer/indexer.routes.ts
  src/listeners/substrate-listener/commands/menstrual-subscription/index.ts
  src/listeners/substrate-listener/commands/menstrual-subscription/menstrual-subscription-added/menstrual-subscription-added.command.ts
  src/listeners/substrate-listener/commands/menstrual-subscription/menstrual-subscription-added/menstrual-subscription-added.handler.ts
  src/listeners/substrate-listener/commands/menstrual-subscription/menstrual-subscription-paid/menstrual-subscription-paid.command.ts
  src/listeners/substrate-listener/commands/menstrual-subscription/menstrual-subscription-paid/menstrual-subscription-paid.handler.ts
  src/listeners/substrate-listener/models/menstrual-subscription-price.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
Labels: fix, feature

#228 fix: reward request service
  package-lock.json
  package.json
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/schedulers/menstrual-subscription/menstrual-subscription.service.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
Labels: fix

#229 fix: amount transaction log menstrual subscription
  src/common/transaction-logging/dto/transaction-logging.dto.ts
  src/common/transaction-logging/transaction-logging.service.ts
  src/common/transaction-status/models/transaction-status.entity.ts
  src/common/transaction-status/models/transaction-status.list.ts
  src/common/transaction-status/transaction-status.module.ts
  src/common/transaction-status/transaction-status.service.ts
  src/common/transaction-type/models/transaction-type.entity.ts
  src/common/transaction-type/models/transaction-type.list.ts
  src/common/transaction-type/transaction-type.module.ts
  src/common/transaction-type/transaction-type.service.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-cancelled/genetic-analysis-order-cancelled.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysys-order-created/genetic-analysis-order-created.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-staked/genetic-analyst-staked.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-unstake/genetic-analyst-unstaked.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-verification-status/genetic-analyst-verification-status.handler.ts
  src/listeners/substrate-listener/commands/genetic-testing/data-staked/data-staked.handler.ts
  src/listeners/substrate-listener/commands/labs/registered/lab-registered.handler.ts
  src/listeners/substrate-listener/commands/labs/retrieve-unstake-amount/retrieve-unstake-amount.handler.ts
  src/listeners/substrate-listener/commands/labs/stake-successfull/stake-successful.handler.ts
  src/listeners/substrate-listener/commands/labs/unstake-successfull/unstaked-successful.handler.ts
  src/listeners/substrate-listener/commands/menstrual-subscription/menstrual-subscription-added/menstrual-subscription-added.handler.ts
  src/listeners/substrate-listener/commands/menstrual-subscription/menstrual-subscription-paid/menstrual-subscription-paid.handler.ts
  src/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-created/order-created.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
  src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-excess/service-request-excess.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-updated/service-request-updated.handler.ts
  test/unit/listeners/substrate-listener/commands/genetic-analyst/genetic-analyst-verification-status/genetic-analyst-verification-status.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.spec.ts
Labels: fix, feature, improvement

#232 fix: error module
  src/common/transaction-logging/transaction-logging.module.ts
  src/schedulers/menstrual-subscription/menstrual-subscription.service.ts
Labels: fix

#230 feat: scheduler inqueue to active
  src/schedulers/menstrual-subscription/menstrual-subscription.service.ts
Labels: feature

#235 fix: currency unit
  src/indexer/events/service-request/commands/update-service-request/update-service-request.handler.ts
  src/listeners/substrate-listener/models/currencyUnit.ts
  test/unit/schedulers/menstrual-subscription/menstrual-subscription.service.spec.ts
Labels: fix, improvement

#237 fix: error listener
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
  src/schedulers/menstrual-subscription/menstrual-subscription.service.ts
Labels: fix

#222 chore(main): release 2.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#247 fix: reward, handle with convert to bigint
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
Labels: fix

#249 fix: add delay between reward
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
Labels: fix

#252 fix: reward failed
  src/common/substrate/command/reward.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  test/unit/common/modules/escrow/escrow.service.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
Labels: fix
