Repository debionetwork/debio-background-worker, pull requests merged in 2022-11, with the labels that each got.

#204 feat: update notification
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysys-order-created/genetic-analysis-order-created.handler.ts
  src/listeners/substrate-listener/commands/orders/order-created/order-created.handler.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
Labels: feature, improvement

#207 fix: Update package polkadot provider
  package-lock.json
  package.json
  src/indexer/models/service-request/request.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.ts
  src/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
  src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.ts
  src/listeners/substrate-listener/commands/service-request/index.ts
  src/listeners/substrate-listener/commands/service-request/service-request-claimed/service-request-claimed.command.ts
  src/listeners/substrate-listener/commands/service-request/service-request-claimed/service-request-claimed.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-processed/service-request-processed.command.ts
  src/listeners/substrate-listener/commands/service-request/service-request-processed/service-request-processed.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.command.ts
  src/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-waiting-for-unstaked/service-request-waiting-for-unstaked.command.ts
  src/listeners/substrate-listener/commands/service-request/service-request-waiting-for-unstaked/service-request-waiting-for-unstaked.handler.ts
  src/listeners/substrate-listener/models/currencyUnit.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-created/order-created.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-created/order-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-failed/order-failed.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-paid/order-paid.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-claimed/service-request-claimed.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-claimed/service-request-claimed.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-processed/service-request-processed.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-processed/service-request-processed.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-wating-for-unstaked/service-request-waiting-for-unstaked.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-wating-for-unstaked/service-request-wating-for-unstaked.handler.spec.ts
  test/unit/mock.ts
Labels: fix

#213 fix: staking request
  src/common/debio-conversion/debio-conversion.service.ts
  src/indexer/events/menstrual-calendar/commands/menstrual-cycle-log-added/menstrual-cycle-log-added.command.ts
  src/indexer/events/menstrual-calendar/commands/menstrual-cycle-log-added/menstrual-cycle-log-added.handler..ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  test/e2e/listeners/substrate-listener/commands/genetic-testing/genetic-testing-events.spec.ts
  test/e2e/listeners/substrate-listener/commands/orders/orders-events.spec.ts
  test/e2e/listeners/substrate-listener/commands/service-request/service-request-events.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
  test/unit/mock.ts
Labels: fix

#214 improvement: update transaction hash from blockchain
  src/indexer/events/orders/commands/order-paid/order-paid.handler.ts
  src/listeners/ethereum-listener/ethereum-listener.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-events.spec.ts
  test/mock/models/genetic-analysts/genetic-analyst-service.mock.ts
  test/unit/listeners/ethereum-listener/ethereum-listener.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
Labels: improvement

#219 feat: update cycle log (effect node pallet events parameter changed)
  src/indexer/events/menstrual-calendar/commands/menstrual-cycle-log-added/menstrual-cycle-log-added.handler..ts
  src/indexer/events/menstrual-calendar/commands/menstrual-cycle-log-updated/menstrual-cycle-log-updated.command.ts
  src/indexer/events/menstrual-calendar/commands/menstrual-cycle-log-updated/menstrual-cycle-log-updated.handler.ts
  src/indexer/events/service-request/commands/update-service-request/update-service-request.command.ts
  src/indexer/events/service-request/commands/update-service-request/update-service-request.handler.ts
  src/indexer/models/service-request/update-service-request.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
  src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-updated/service-request-updated.command.ts
  test/unit/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-created/order-created.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-created/order-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-failed/order-failed.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-paid/order-paid.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.spec.ts
  test/unit/mock.ts
Labels: feature, improvement

#220 fix: scheduler log error
  src/schedulers/genetic-analyst-unstaked/unstaked.service.ts
  src/schedulers/lab-unstake/lab-unstake.service.ts
  src/schedulers/menstrual-subscription/menstrual-subscription.service.ts
  src/schedulers/unstaked/unstaked.service.ts
  test/unit/mock.ts
Labels: fix

#185 chore(main): release 2.2.0
  CHANGELOG.md
Labels: autorelease: pending
