Repository debionetwork/debio-background-worker, pull requests merged in 2022-07, with the labels that each got.

#104 fix: claimed and update polkadot api
  .github/CODEOWNERS
  babel.config.js
  package-lock.json
  package.json
  src/substrate/events/service-request/commands/claimed-service-request/claimed-service-request.handler.ts
  src/substrate/events/service-request/commands/finalized-service-request/finalized-service-request.handler.ts
  src/substrate/events/service-request/commands/processed-service-request/processed-service-request.handler.ts
  src/substrate/events/service-request/commands/unstaked-service-request/unstaked-service-request.handler.ts
  src/substrate/substrate.handler.ts
  test/e2e/config.ts
  test/e2e/docker-compose.yml
  test/e2e/elasticsearch-fixture.ts
  test/e2e/jest-e2e-substrate.json
  test/e2e/jest-e2e.json
  test/e2e/listener-test-sequencer.js
  test/e2e/polkadot-init.ts
  test/e2e/setup.ts
  test/e2e/substrate-fixture.ts
  test/e2e/substrate.e2e-spec.ts
  test/e2e/substrate/events/service-request/service-request-claimed.spec.ts
  test/e2e/teardown.ts
  test/mock/models/labs/labs.mock.ts
  test/mock/models/labs/service.mock.ts
  test/mock/models/service-request/service-request.mock.ts
  test/unit/events/service-request/service-request.handler.spec.ts
  yarn.lock
Labels: fix, test

#105 fix: fetch on start application
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/substrate/substrate.handler.ts
  yarn.lock
Labels: fix

#106 fix: remove unused params
  src/substrate/events/service-request/commands/claimed-service-request/claimed-service-request.handler.ts
  src/substrate/events/service-request/commands/finalized-service-request/finalized-service-request.handler.ts
  src/substrate/events/service-request/commands/processed-service-request/processed-service-request.handler.ts
  src/substrate/events/service-request/commands/unstaked-service-request/unstaked-service-request.handler.ts
  src/substrate/substrate.handler.ts
  test/e2e/substrate/events/service-request/service-request-claimed.spec.ts
Labels: fix

#108 ci: improve github workflows
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: ci

#109 ci: update version & formatting
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
  .github/workflows/update-version.yml
Labels: ci

#110 ci: fix create tags & release
  .github/workflows/create-tags.yml
  .github/workflows/release.yml
Labels: ci

#111 fix: wording service request created
  src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.spec.ts
Labels: fix

#114 ci: revert "fix create tags & release"
  .github/workflows/create-tags.yml
  .github/workflows/release.yml
Labels: ci

#115 ci: revert "update version & formatting"
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
  .github/workflows/update-version.yml
Labels: ci

#113 feat: add field block_number to Notification entity
  package-lock.json
  src/common/caches/index.ts
  src/common/debio-conversion/debio-conversion.service.ts
  src/common/notification/dto/notification.dto.ts
  src/common/notification/models/notification.entity.ts
  src/common/notification/models/response.ts
  src/common/notification/notification.service.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysys-order-created/genetic-analysis-order-created.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-rejected/genetic-analysis-rejected.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-resultready/genetic-analysis-result-ready.handler.ts
  src/listeners/substrate-listener/commands/genetic-analyst-services/genetic-analyst-service-created/genetic-analyst-service-created.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-registered/genetic-analyst-registered.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-verification-status/genetic-analyst-verification-status.handler.ts
  src/listeners/substrate-listener/commands/genetic-testing/dna-sample-rejected/dna-sample-rejected.handler.ts
  src/listeners/substrate-listener/commands/genetic-testing/dna-sample-result-ready/dna-sample-result-ready.handler.ts
  src/listeners/substrate-listener/commands/labs/registered/lab-registered.handler.ts
  src/listeners/substrate-listener/commands/labs/update-verification-status/update-verification-status.handler.ts
  src/listeners/substrate-listener/commands/orders/order-created/order-created.handler.ts
  src/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
  src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-claimed/service-request-claimed.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-excess/service-request-excess.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-partial/service-request-partial.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded/service-request-staking-amount-refunded.handler.ts
  src/listeners/substrate-listener/commands/services/service-created/service-created.handler.ts
  test/mock/models/notification/notification.entity.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analyst-services/genetic-analyst-service-created/genetic-analyst-service-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-testing/dna-sample-rejected/dna-sample-rejected.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-testing/dna-sample-result-ready/dna-sample-result-ready.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-claimed/service-request-claimed.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded/service-request-staking-amount-refunded.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/services/service-created/service-created.handler.spec.ts
  yarn.lock
Labels: feature, test

#116 ci: revert "improve github workflows"
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: ci

#112 fix: undo some google secret manager to process env and integration test substrate listener
  src/common/caches/index.ts
  src/common/escrow/escrow.module.ts
  src/common/notification/notification.service.ts
  src/common/substrate/index.ts
  src/common/substrate/substrate.service.ts
  src/indexer/events/labs/commands/lab-update-verification-status/lab-update-verification-status.handler.ts
  src/indexer/events/labs/commands/lab-updated/lab-updated.handler.ts
  src/indexer/indexer.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysts/index.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-claimed/service-request-claimed.command.ts
  src/listeners/substrate-listener/commands/service-request/service-request-claimed/service-request-claimed.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-excess/service-request-excess.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-partial/service-request-partial.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded/service-request-staking-amount-refunded.command.ts
  src/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded/service-request-staking-amount-refunded.handler.ts
  src/listeners/substrate-listener/commands/services/service-created/service-created.handler.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  test/e2e/elasticsearch-fixture.indexer.ts
  test/e2e/indexer-test-sequencer.js
  test/e2e/indexer/events/labs/lab-deregistered.spec.ts
  test/e2e/indexer/events/labs/lab-registered.spec.ts
  test/e2e/indexer/events/labs/lab-update-verification-status.spec.ts
  test/e2e/indexer/events/labs/lab-updated.spec.ts
  test/e2e/indexer/events/service-request/service-request-claimed.spec.ts
  test/e2e/jest-e2e-indexer.json
  test/e2e/listener-test-sequencer.js
  test/e2e/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-created.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-rejected.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analyst-service/genetic-analyst-service-created.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-registered.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-verification-status.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-testing/data-staked.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-testing/dna-sample-rejected.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-testing/dna-sample-result-ready.spec.ts
  test/e2e/listeners/substrate-listener/commands/labs/stake-successful.spec.ts
  test/e2e/listeners/substrate-listener/commands/labs/unstake-successful.spec.ts
  test/e2e/listeners/substrate-listener/commands/labs/update-verification-status.spec.ts
  test/e2e/listeners/substrate-listener/commands/orders/order-failed.spec.ts
  test/e2e/listeners/substrate-listener/commands/orders/order-fulfilled.spec.ts
  test/e2e/listeners/substrate-listener/commands/orders/order-paid.spec.ts
  test/e2e/listeners/substrate-listener/commands/service-request/service-request-claimed.spec.ts
  test/e2e/listeners/substrate-listener/commands/service-request/service-request-excess.spec.ts
  test/e2e/listeners/substrate-listener/commands/service-request/service-request-partial.spec.ts
  test/e2e/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded.spec.ts
  test/e2e/listeners/substrate-listener/commands/services/service-created.spec.ts
  test/e2e/schedulers/lab-unstake.spec.ts
  test/e2e/schedulers/mailer.spec.ts
  test/e2e/schedulers/unstaked.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-claimed/service-request-claimed.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-claimed/service-request-claimed.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded/service-request-staking-amount-refunded.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded/service-request-staking-amount-refunded.handler.spec.ts
Labels: fix, feature, test

#117 ci: added new env google project id
  .github/workflows/deployer.yml
  .maintain/docker/build-image.sh
  .maintain/docker/docker-compose.yml
  .maintain/docker/start-docker-compose.sh
  .maintain/docker/stop-docker-compose.sh
  README.md
  package.json
Labels: ci

#118 ci: fixed project permission
  .github/workflows/deployer.yml
Labels: ci

#119 ci: added gca
  .github/workflows/deployer.yml
Labels: ci

#120 ci: fix helm upgrade
  .github/workflows/deployer.yml
Labels: ci

#121 fix: update database using env to google secret manager
  src/app.module.ts
  src/common/proxies/process-env/process-env.module.ts
  src/schedulers/genetic-analyst-unstaked/unstaked.service.ts
  src/schedulers/lab-unstake/lab-unstake.service.ts
  src/schedulers/unstaked/unstaked.service.ts
  test/e2e/schedulers/lab-unstake.spec.ts
  test/e2e/schedulers/unstaked.spec.ts
  test/unit/schedulers/lab/lab-unstake.service.spec.ts
  test/unit/schedulers/unstaked/unstaked.service.spec.ts
Labels: fix

#123 fix: failing start builds
  package-lock.json
  package.json
  src/app.module.ts
  src/common/caches/index.ts
  src/common/common.module.ts
  src/common/debio-conversion/debio-conversion.module.ts
  src/common/escrow/escrow.module.ts
  src/common/ethereum/ethereum.module.ts
  src/common/mailer/mailer.module.ts
  src/common/substrate/index.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
  src/schedulers/schedulers.module.ts
  yarn.lock
Labels: fix, test

#124 ci: added db name
  .github/workflows/deployer.yml
Labels: ci

#125 ci: added db host
  .github/workflows/deployer.yml
Labels: ci

#127 chore: bump version to 2.1.4
  package-lock.json
  package.json
  yarn.lock
Labels: feature

#126 test: indexer integration test
  src/indexer/events/genetic-analysts/commands/genetic-analysts-retrieve-unstake-amount/genetic-analysts-retrieve-unstake-amount.handler.ts
  src/indexer/events/genetic-analysts/commands/genetic-analysts-unstake-successful/genetic-analysts-unstake-successful.handler.ts
  src/indexer/events/genetic-analysts/commands/genetic-analysts-verification-failed/genetic-analysts-verification-failed.handler.ts
  src/indexer/models/certification/certification.ts
  src/listeners/substrate-listener/commands/genetic-testing/data-staked/data-staked.handler.ts
  test/e2e/indexer-test-sequencer.js
  test/e2e/indexer/events/certification-events.spec.ts
  test/e2e/indexer/events/genetic-analyst-events.spec.ts
  test/e2e/indexer/events/genetic-data-events.spec.ts
  test/e2e/indexer/events/genetic-testing-events.spec.ts
  test/e2e/indexer/events/labs-events.spec.ts
  test/e2e/indexer/events/labs/lab-deregistered.spec.ts
  test/e2e/indexer/events/labs/lab-registered.spec.ts
  test/e2e/indexer/events/labs/lab-update-verification-status.spec.ts
  test/e2e/indexer/events/labs/lab-updated.spec.ts
  test/e2e/indexer/events/orders-events.spec.ts
  test/e2e/indexer/events/service-events.spec.ts
  test/e2e/indexer/events/service-request-events.spec.ts
  test/e2e/listeners/substrate-listener/commands/genetic-testing/data-staked.spec.ts
  test/mock/models/certifications/certification-mock.ts
Labels: fix, test

#135 fix: rename set block number
  src/indexer/blocks/commands/set-last-substrate-block-old/set-last-substrate-block-old.command.ts
  src/indexer/blocks/commands/set-last-substrate-block-old/set-last-substrate-block-old.handler.ts
  src/indexer/blocks/commands/set-last-substrate-block/set-last-substrate-block.command.ts
  src/indexer/blocks/commands/set-last-substrate-block/set-last-substrate-block.handler.ts
  src/indexer/indexer.handler.ts
Labels: fix
